services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo-cluster

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    ports:
      - 27018:27017
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo-cluster

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    ports:
      - 27019:27017
    command: ["mongod", "--replSet", "rs0"]
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo-cluster

  mongoinit:
    image: mongo:6.0
    container_name: mongoinit
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      bash -c '
      echo "Waiting for MongoDB to start...";
      sleep 5;
      mongosh --host mongo1 --eval "
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:27017\", priority: 2 },
            { _id: 1, host: \"mongo2:27017\", priority: 1 },
            { _id: 2, host: \"mongo3:27017\", priority: 1 }
          ]
        }, { force: true });
        rs.status();
      ";
      '
    networks:
      - mongo-cluster

networks:
  mongo-cluster:

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
